export const INITIALIZE = 'INITIALIZE';
export const RESET = 'RESET';
export const SETUP_ACCOUNT = 'SETUP_ACCOUNT';
export const MANAGE_ACCOUNT = 'MANAGE_ACCOUNT';
export const MANAGE_ACCOUNT_DEVICES = 'MANAGE_ACCOUNT_DEVICES';
export const ACCOUNT_TRANSACTIONS = 'ACCOUNT_TRANSACTIONS';
